//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasoEstudio01.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CasoEstudioEntities : DbContext
    {
        public CasoEstudioEntities()
            : base("name=CasoEstudioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<TiposCursos> TiposCursos { get; set; }
    
        public virtual int sp_RegistrarMatricula(string identificacion, Nullable<decimal> monto, Nullable<int> tipoCurso)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var tipoCursoParameter = tipoCurso.HasValue ?
                new ObjectParameter("TipoCurso", tipoCurso) :
                new ObjectParameter("TipoCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarMatricula", identificacionParameter, montoParameter, tipoCursoParameter);
        }
    
        public virtual int sp_RegistrarM(string identificacion, Nullable<decimal> monto, Nullable<int> tipoCurso)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var tipoCursoParameter = tipoCurso.HasValue ?
                new ObjectParameter("TipoCurso", tipoCurso) :
                new ObjectParameter("TipoCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarM", identificacionParameter, montoParameter, tipoCursoParameter);
        }
    
        public virtual ObjectResult<sp_ListarMatriculas_Result> sp_ListarMatriculas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarMatriculas_Result>("sp_ListarMatriculas");
        }
    }
}
